theme: jekyll-theme-minimal
title: Timothy Regis
description: Highly motivated individual with strong work ethic and ability to work in a rapidly changing environment. Exceptional organizational and communication skills with experience in improving processes.
